package com.app.use.common.util;

import org.springframework.stereotype.Component;

@Component
public class WeatherUtil {

	public String getWeatherId(String message) {
		if (message.matches(".*" +"稚内" +".*")) {return"011000";}
		if (message.matches(".*" +"旭川" +".*")) {return"012010";}
		if (message.matches(".*" +"留萌" +".*")) {return"012020";}
		if (message.matches(".*" +"網走" +".*")) {return"013010";}
		if (message.matches(".*" +"北見" +".*")) {return"013020";}
		if (message.matches(".*" +"紋別" +".*")) {return"013030";}
		if (message.matches(".*" +"根室" +".*")) {return"014010";}
		if (message.matches(".*" +"釧路" +".*")) {return"014020";}
		if (message.matches(".*" +"帯広" +".*")) {return"014030";}
		if (message.matches(".*" +"室蘭" +".*")) {return"015010";}
		if (message.matches(".*" +"浦河" +".*")) {return"015020";}
		if (message.matches(".*" +"札幌" +".*")) {return"016010";}
		if (message.matches(".*" +"岩見沢" +".*")) {return"016020";}
		if (message.matches(".*" +"倶知安" +".*")) {return"016030";}
		if (message.matches(".*" +"函館" +".*")) {return"017010";}
		if (message.matches(".*" +"江差" +".*")) {return"017020";}
		if (message.matches(".*" +"青森" +".*")) {return"020010";}
		if (message.matches(".*" +"むつ" +".*")) {return"020020";}
		if (message.matches(".*" +"八戸" +".*")) {return"020030";}
		if (message.matches(".*" +"盛岡" +".*")) {return"030010";}
		if (message.matches(".*" +"宮古" +".*")) {return"030020";}
		if (message.matches(".*" +"大船渡" +".*")) {return"030030";}
		if (message.matches(".*" +"仙台" +".*")) {return"040010";}
		if (message.matches(".*" +"白石" +".*")) {return"040020";}
		if (message.matches(".*" +"秋田" +".*")) {return"050010";}
		if (message.matches(".*" +"横手" +".*")) {return"050020";}
		if (message.matches(".*" +"山形" +".*")) {return"060010";}
		if (message.matches(".*" +"米沢" +".*")) {return"060020";}
		if (message.matches(".*" +"酒田" +".*")) {return"060030";}
		if (message.matches(".*" +"新庄" +".*")) {return"060040";}
		if (message.matches(".*" +"福島" +".*")) {return"070010";}
		if (message.matches(".*" +"小名浜" +".*")) {return"070020";}
		if (message.matches(".*" +"若松" +".*")) {return"070030";}
		if (message.matches(".*" +"水戸" +".*")) {return"080010";}
		if (message.matches(".*" +"土浦" +".*")) {return"080020";}
		if (message.matches(".*" +"宇都宮" +".*")) {return"090010";}
		if (message.matches(".*" +"大田原" +".*")) {return"090020";}
		if (message.matches(".*" +"前橋" +".*")) {return"100010";}
		if (message.matches(".*" +"みなかみ" +".*")) {return"100020";}
		if (message.matches(".*" +"さいたま" +".*")) {return"110010";}
		if (message.matches(".*" +"熊谷" +".*")) {return"110020";}
		if (message.matches(".*" +"秩父" +".*")) {return"110030";}
		if (message.matches(".*" +"千葉" +".*")) {return"120010";}
		if (message.matches(".*" +"銚子" +".*")) {return"120020";}
		if (message.matches(".*" +"館山" +".*")) {return"120030";}
		if (message.matches(".*" +"東京" +".*")) {return"130010";}
		if (message.matches(".*" +"大島" +".*")) {return"130020";}
		if (message.matches(".*" +"八丈島" +".*")) {return"130030";}
		if (message.matches(".*" +"父島" +".*")) {return"130040";}
		if (message.matches(".*" +"横浜" +".*")) {return"140010";}
		if (message.matches(".*" +"小田原" +".*")) {return"140020";}
		if (message.matches(".*" +"新潟" +".*")) {return"150010";}
		if (message.matches(".*" +"長岡" +".*")) {return"150020";}
		if (message.matches(".*" +"高田" +".*")) {return"150030";}
		if (message.matches(".*" +"相川" +".*")) {return"150040";}
		if (message.matches(".*" +"富山" +".*")) {return"160010";}
		if (message.matches(".*" +"伏木" +".*")) {return"160020";}
		if (message.matches(".*" +"金沢" +".*")) {return"170010";}
		if (message.matches(".*" +"輪島" +".*")) {return"170020";}
		if (message.matches(".*" +"福井" +".*")) {return"180010";}
		if (message.matches(".*" +"敦賀" +".*")) {return"180020";}
		if (message.matches(".*" +"甲府" +".*")) {return"190010";}
		if (message.matches(".*" +"河口湖" +".*")) {return"190020";}
		if (message.matches(".*" +"長野" +".*")) {return"200010";}
		if (message.matches(".*" +"松本" +".*")) {return"200020";}
		if (message.matches(".*" +"飯田" +".*")) {return"200030";}
		if (message.matches(".*" +"岐阜" +".*")) {return"210010";}
		if (message.matches(".*" +"高山" +".*")) {return"210020";}
		if (message.matches(".*" +"静岡" +".*")) {return"220010";}
		if (message.matches(".*" +"網代" +".*")) {return"220020";}
		if (message.matches(".*" +"三島" +".*")) {return"220030";}
		if (message.matches(".*" +"浜松" +".*")) {return"220040";}
		if (message.matches(".*" +"名古屋" +".*")) {return"230010";}
		if (message.matches(".*" +"豊橋" +".*")) {return"230020";}
		if (message.matches(".*" +"津" +".*")) {return"240010";}
		if (message.matches(".*" +"尾鷲" +".*")) {return"240020";}
		if (message.matches(".*" +"大津" +".*")) {return"250010";}
		if (message.matches(".*" +"彦根" +".*")) {return"250020";}
		if (message.matches(".*" +"京都" +".*")) {return"260010";}
		if (message.matches(".*" +"舞鶴" +".*")) {return"260020";}
		if (message.matches(".*" +"大阪" +".*")) {return"270000";}
		if (message.matches(".*" +"神戸" +".*")) {return"280010";}
		if (message.matches(".*" +"豊岡" +".*")) {return"280020";}
		if (message.matches(".*" +"奈良" +".*")) {return"290010";}
		if (message.matches(".*" +"風屋" +".*")) {return"290020";}
		if (message.matches(".*" +"和歌山" +".*")) {return"300010";}
		if (message.matches(".*" +"潮岬" +".*")) {return"300020";}
		if (message.matches(".*" +"鳥取" +".*")) {return"310010";}
		if (message.matches(".*" +"米子" +".*")) {return"310020";}
		if (message.matches(".*" +"松江" +".*")) {return"320010";}
		if (message.matches(".*" +"浜田" +".*")) {return"320020";}
		if (message.matches(".*" +"西郷" +".*")) {return"320030";}
		if (message.matches(".*" +"岡山" +".*")) {return"330010";}
		if (message.matches(".*" +"津山" +".*")) {return"330020";}
		if (message.matches(".*" +"広島" +".*")) {return"340010";}
		if (message.matches(".*" +"庄原" +".*")) {return"340020";}
		if (message.matches(".*" +"下関" +".*")) {return"350010";}
		if (message.matches(".*" +"山口" +".*")) {return"350020";}
		if (message.matches(".*" +"柳井" +".*")) {return"350030";}
		if (message.matches(".*" +"萩" +".*")) {return"350040";}
		if (message.matches(".*" +"徳島" +".*")) {return"360010";}
		if (message.matches(".*" +"日和佐" +".*")) {return"360020";}
		if (message.matches(".*" +"高松" +".*")) {return"370000";}
		if (message.matches(".*" +"松山" +".*")) {return"380010";}
		if (message.matches(".*" +"新居浜" +".*")) {return"380020";}
		if (message.matches(".*" +"宇和島" +".*")) {return"380030";}
		if (message.matches(".*" +"高知" +".*")) {return"390010";}
		if (message.matches(".*" +"室戸岬" +".*")) {return"390020";}
		if (message.matches(".*" +"清水" +".*")) {return"390030";}
		if (message.matches(".*" +"福岡" +".*")) {return"400010";}
		if (message.matches(".*" +"八幡" +".*")) {return"400020";}
		if (message.matches(".*" +"飯塚" +".*")) {return"400030";}
		if (message.matches(".*" +"久留米" +".*")) {return"400040";}
		if (message.matches(".*" +"佐賀" +".*")) {return"410010";}
		if (message.matches(".*" +"伊万里" +".*")) {return"410020";}
		if (message.matches(".*" +"長崎" +".*")) {return"420010";}
		if (message.matches(".*" +"佐世保" +".*")) {return"420020";}
		if (message.matches(".*" +"厳原" +".*")) {return"420030";}
		if (message.matches(".*" +"福江" +".*")) {return"420040";}
		if (message.matches(".*" +"熊本" +".*")) {return"430010";}
		if (message.matches(".*" +"阿蘇乙姫" +".*")) {return"430020";}
		if (message.matches(".*" +"牛深" +".*")) {return"430030";}
		if (message.matches(".*" +"人吉" +".*")) {return"430040";}
		if (message.matches(".*" +"大分" +".*")) {return"440010";}
		if (message.matches(".*" +"中津" +".*")) {return"440020";}
		if (message.matches(".*" +"日田" +".*")) {return"440030";}
		if (message.matches(".*" +"佐伯" +".*")) {return"440040";}
		if (message.matches(".*" +"宮崎" +".*")) {return"450010";}
		if (message.matches(".*" +"延岡" +".*")) {return"450020";}
		if (message.matches(".*" +"都城" +".*")) {return"450030";}
		if (message.matches(".*" +"高千穂" +".*")) {return"450040";}
		if (message.matches(".*" +"鹿児島" +".*")) {return"460010";}
		if (message.matches(".*" +"鹿屋" +".*")) {return"460020";}
		if (message.matches(".*" +"種子島" +".*")) {return"460030";}
		if (message.matches(".*" +"名瀬" +".*")) {return"460040";}
		if (message.matches(".*" +"那覇" +".*")) {return"471010";}
		if (message.matches(".*" +"名護" +".*")) {return"471020";}
		if (message.matches(".*" +"久米島" +".*")) {return"471030";}
		if (message.matches(".*" +"南大東" +".*")) {return"472000";}
		if (message.matches(".*" +"宮古島" +".*")) {return"473000";}
		if (message.matches(".*" +"石垣島" +".*")) {return"474010";}
		if (message.matches(".*" +"与那国島" +".*")) {return"474020";}
		return "";
	}
}
